import { IProduct } from "../interface";

export const products: IProduct[] = [
	{
		id: 1,
		name: "Adicolor Classics Joggers",
		image: "/images/img/15.png",
		price: 63.85,
		label: {
			id: 1,
			label: "HOT",
			color: "#FF6F61",
		},
		brand: {
			id: 1,
			name: "Dress",
			slug: "dress",
			image: "/images/brand/01.png",
		},
		category_id: 2,
	},
	{
		id: 2,
		name: "Nike Sportswear Futura Luxe",
		image: "/images/img/14.png",
		price: 130.0,
		sale_price: 120.0,
		label: {
			id: 1,
			label: "Sale",
			color: "#1E2832",
		},
		brand: {
			id: 2,
			name: "Bag",
			slug: "bag",
			image: "/images/brand/02.png",
		},
		category_id: 3,
	},
	{
		id: 3,
		name: "Adicolor Classics Joggers",
		image: "/images/img/13.png",
		price: 63.85,
		label: {
			id: 1,
			label: "HOT",
			color: "#FF6F61",
		},
		brand: {
			id: 3,
			name: "Scraf",
			slug: "scraf",
			image: "/images/brand/03.png",
		},
		category_id: 1,
	},
	{
		id: 4,
		name: "Yellow Reserved Hoodie",
		image: "/images/img/04.png",
		price: 364.0,
		sale_price: 155.0,
		label: {
			id: 1,
			label: "Sale",
			color: "#FF6F61",
		},
		brand: {
			id: 4,
			name: "Dress",
			slug: "dress",
			image: "/images/brand/04.png",
		},
		category_id: 3,
	},
	{
		id: 5,
		name: "Adicolor Classics Joggers",
		image: "/images/img/11.png",
		price: 63.85,
		label: {
			id: 1,
			label: "HOT",
			color: "#FF6F61",
		},
		brand: {
			id: 1,
			name: "Dress",
			slug: "dress",
			image: "/images/brand/01.png",
		},
		category_id: 1,
	},
	{
		id: 6,
		name: "Nike Sportswear Futura Luxe",
		image: "/images/img/12.png",
		price: 130.0,
		sale_price: 120.0,
		label: {
			id: 1,
			label: "Sale",
			color: "#1E2832",
		},
		brand: {
			id: 2,
			name: "Bag",
			slug: "bag",
			image: "/images/brand/02.png",
		},
		category_id: 2,
	},
	{
		id: 7,
		name: "Adicolor Classics Joggers",
		image: "/images/img/17.png",
		price: 63.85,
		label: {
			id: 1,
			label: "HOT",
			color: "#FF6F61",
		},
		brand: {
			id: 3,
			name: "Scraf",
			slug: "scraf",
			image: "/images/brand/03.png",
		},
		category_id: 3,
	},
	{
		id: 8,
		name: "Yellow Reserved Hoodie",
		image: "/images/img/16.png",
		price: 364.0,
		sale_price: 155.0,
		label: {
			id: 1,
			label: "Sale",
			color: "#FF6F61",
		},
		brand: {
			id: 4,
			name: "Dress",
			slug: "dress",
			image: "/images/brand/04.png",
		},
		category_id: 2,
	},

	{
		id: 9,
		name: "Adicolor Classics Joggers",
		image: "/images/img/01.png",
		price: 63.85,
		label: {
			id: 1,
			label: "HOT",
			color: "#FF6F61",
		},
		brand: {
			id: 1,
			name: "Dress",
			slug: "dress",
			image: "/images/brand/01.png",
		},
		category_id: 1,
	},
	{
		id: 10,
		name: "Nike Sportswear Futura Luxe",
		image: "/images/img/02.png",
		price: 130.0,
		sale_price: 120.0,
		label: {
			id: 1,
			label: "Sale",
			color: "#1E2832",
		},
		brand: {
			id: 2,
			name: "Bag",
			slug: "bag",
			image: "/images/brand/02.png",
		},
		category_id: 1,
	},
	{
		id: 11,
		name: "Adicolor Classics Joggers",
		image: "/images/img/03.png",
		price: 63.85,
		label: {
			id: 1,
			label: "HOT",
			color: "#FF6F61",
		},
		brand: {
			id: 3,
			name: "Scraf",
			slug: "scraf",
			image: "/images/brand/03.png",
		},
		category_id: 3,
	},
	{
		id: 12,
		name: "Yellow Reserved Hoodie",
		image: "/images/img/04.png",
		price: 364.0,
		sale_price: 155.0,
		label: {
			id: 1,
			label: "Sale",
			color: "#FF6F61",
		},
		brand: {
			id: 4,
			name: "Dress",
			slug: "dress",
			image: "/images/brand/04.png",
		},
		category_id: 3,
	},
	{
		id: 13,
		name: "Adicolor Classics Joggers",
		image: "/images/img/07.png",
		price: 63.85,
		label: {
			id: 1,
			label: "HOT",
			color: "#FF6F61",
		},
		brand: {
			id: 1,
			name: "Dress",
			slug: "dress",
			image: "/images/brand/01.png",
		},
		category_id: 2,
	},
	{
		id: 14,
		name: "Nike Sportswear Futura Luxe",
		image: "/images/img/08.png",
		price: 130.0,
		sale_price: 120.0,
		label: {
			id: 1,
			label: "Sale",
			color: "#1E2832",
		},
		brand: {
			id: 2,
			name: "Bag",
			slug: "bag",
			image: "/images/brand/02.png",
		},
		category_id: 2,
	},
	{
		id: 15,
		name: "Adicolor Classics Joggers",
		image: "/images/img/03.png",
		price: 63.85,
		label: {
			id: 1,
			label: "HOT",
			color: "#FF6F61",
		},
		brand: {
			id: 3,
			name: "Scraf",
			slug: "scraf",
			image: "/images/brand/03.png",
		},
	},
	{
		id: 16,
		name: "Yellow Reserved Hoodie",
		image: "/images/img/09.png",
		price: 364.0,
		sale_price: 155.0,
		label: {
			id: 1,
			label: "Sale",
			color: "#FF6F61",
		},
		brand: {
			id: 4,
			name: "Dress",
			slug: "dress",
			image: "/images/brand/04.png",
		},
		category_id: 2,
	},
];
