import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Header from "@components/Header";
import Footer from "@components/Footer";
import { Open_Sans as OpenSans, Roboto } from "next/font/google";

// const geistSans = localFont({
// 	src: "./fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "./fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });

const openSans = OpenSans({
	subsets: ["latin"],
	weight: ["400", "600", "700"],
	variable: "--font-open-sans",
});

const roboto = Roboto({
	subsets: ["latin", "latin"],
	weight: ["300", "400", "500", "700"],
	variable: "--font-roboto",
});

export const metadata: Metadata = {
	title: "Coral Collection App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={` ${openSans.variable} ${roboto.variable} antialiased`}>
				<Header />
				<main className="main-container relative z-10">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
